language: python
# Switch to container-based builds
sudo: false
# Which versions of Python to test
python:
  - "2.7"
  - "3.6"
# Allow Python3 tests to fail for now
#matrix:
#  allow_failures:
#    - python: "3.6"
# Do not have the virtualenv use system-wide site packages
virtualenv:
    system_site_packages: false
# command to install dependencies
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
#  - conda update -q conda
  - conda info -a
  # These are the packages we need
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda create -q -c menpo -n test-environment python=$TRAVIS_PYTHON_VERSION opencv=2.4.11;
    else
      conda create -q -c conda-forge -n test-environment python=$TRAVIS_PYTHON_VERSION opencv=3.3.0;
    fi
  - source activate test-environment
  - pip install coveralls matplotlib scipy scikit-image pytest pandas
# Install PlantCV
install:
  - python setup.py install
# command to run tests
script:
  - source activate test-environment
  - coverage run --source=plantcv setup.py test
  # - py.test -v tests/tests.py
after_success:
  coveralls
# Which branches to run build tests on
branches:
  only:
    - master
