COLOR2GRAY_HSV_H = 'h'
COLOR2GRAY_HSV_S = 's'
COLOR2GRAY_HSV_V = 'v'

COLOR2GRAY_LAB_L = 'l'
COLOR2GRAY_LAB_A = 'a'
COLOR2GRAY_LAB_B = 'b'

COLOR2GRAY_RGB_B = 'b'
COLOR2GRAY_RGB_G = 'g'
COLOR2GRAY_RGB_R = 'r'

THRESHOLD_OBJ_DARK = 'dark'
THRESHOLD_OBJ_LIGHT = 'light'

APPLY_MASK_WHITE = 'white'
APPLY_MASK_BLACK = 'black'

DEFINE_ROI_SHAPE_RECT = 'rectangle'
DEFINE_ROI_SHAPE_CIRCLE = 'circle'
DEFINE_ROI_INPUT_BINARY = 'binary'
DEFINE_ROI_INPUT_RGB = 'rgb'

DEBUG_PRINT = 'print'
DEBUG_PLOT = 'plot'