import cv2

COLOR2GRAY_HSV_H = 'h'
COLOR2GRAY_HSV_S = 's'
COLOR2GRAY_HSV_V = 'v'

COLOR2GRAY_LAB_L = 'l'
COLOR2GRAY_LAB_A = 'a'
COLOR2GRAY_LAB_B = 'b'

COLOR2GRAY_RGB_B = 'b'
COLOR2GRAY_RGB_G = 'g'
COLOR2GRAY_RGB_R = 'r'

THRESHOLD_OBJ_DARK = 'dark'
THRESHOLD_OBJ_LIGHT = 'light'

APPLY_MASK_WHITE = 'white'
APPLY_MASK_BLACK = 'black'
COLOR_BLACK = 'black'
COLOR_WHITE = 'white'
COLOUR_BLACK = 'black'
COLOUR_WHITE = 'white'

COLOR_MAP_GRAY = 'gray'
COLOUR_MAP_GREY = 'gray'

DEFINE_ROI_SHAPE_RECT = 'rectangle'
DEFINE_ROI_SHAPE_CIRCLE = 'circle'
DEFINE_ROI_INPUT_BINARY = 'binary'
DEFINE_ROI_INPUT_RGB = 'rgb'

MASK_WHITE = 'white' 
MASK_BLACK = 'black'
#RECT_MASK_GREY = 'grey'

ROI_OBJECTS_TYPE_CUTTO = 'cutto'
ROI_OBJECTS_TYPE_PARTIAL = 'partial'
ROI_OBJECTS_TYPE_MASSC = 'massc'

SHIFT_IMG_TOP = 'top'
SHIFT_IMG_BOTTOM = 'bottom'
SHIFT_IMG_LEFT = 'left'
SHIFT_IMG_RIGHT = 'right'

REPORT_SIZE_MARKER_DETECT = 'detect'
REPORT_SIZE_MARKER_DEFINE = 'define'

DEBUG_PRINT = 'print'
DEBUG_PLOT = 'plot'

READ_IMAGE_GRAY = 'GRAY'
READ_IMAGE_GREY = 'GRAY'
READ_IMAGE_RGB = 'RGB'

WHITE_BALANCE_HIST = 'hist'
WHITE_BALANCE_MAX = 'max'

## collect cv2 version info
try:
    CV2MAJOR, CV2MINOR, _, _ = cv2.__version__.split('.')
except:
    CV2MAJOR, CV2MINOR, _ = cv2.__version__.split('.')
CV2MAJOR, CV2MINOR = int(CV2MAJOR), int(CV2MINOR)