import cv2

COLOR2GRAY_HSV_H = 'h'
COLOR2GRAY_HSV_S = 's'
COLOR2GRAY_HSV_V = 'v'

COLOR2GRAY_LAB_L = 'l'
COLOR2GRAY_LAB_A = 'a'
COLOR2GRAY_LAB_B = 'b'

COLOR2GRAY_RGB_B = 'b'
COLOR2GRAY_RGB_G = 'g'
COLOR2GRAY_RGB_R = 'r'

THRESHOLD_OBJ_DARK = 'DARK'
THRESHOLD_OBJ_LIGHT = 'LIGHT'

APPLY_MASK_WHITE = 'WHITE'
APPLY_MASK_BLACK = 'BLACK'
COLOR_BLACK = 'BLACK'
COLOR_WHITE = 'WHITE'
COLOUR_BLACK = 'BLACK'
COLOUR_WHITE = 'WHITE'
COLOUR_GRAY = 'GRAY'
COLOUR_GREY = 'GRAY'
COLOR_GRAY = 'GRAY'
COLOR_GREY = 'GRAY'

COLOR_MAP_GRAY = 'gray'
COLOUR_MAP_GREY = 'gray'

DEFINE_ROI_SHAPE_RECT = 'RECTANGLE'
DEFINE_ROI_SHAPE_CIRCLE = 'CIRCLE'
DEFINE_ROI_INPUT_BINARY = 'BINARY'
DEFINE_ROI_INPUT_RGB = 'RGB'

RECT_MASK_WHITE = 'WHITE' 
RECT_MASK_BLACK = 'BLACK'
RECT_MASK_GREY = 'GRAY'
RECT_MASK_GRAY = 'GRAY'

ROI_OBJECTS_TYPE_CUTTO = 'CUTTO'
ROI_OBJECTS_TYPE_PARTIAL = 'PARTIAL'
ROI_OBJECTS_TYPE_MASSC = 'MASSC'
ROI_OBJECTS_TYPE_LARGEST = 'LARGEST'
ROI_OBJECTS_TYPE_50PCT = '50PCT'

SHIFT_IMG_TOP = 'TOP'
SHIFT_IMG_BOTTOM = 'BOTTOM'
SHIFT_IMG_LEFT = 'LEFT'
SHIFT_IMG_RIGHT = 'RIGHT'

REPORT_SIZE_MARKER_DETECT = 'DETECT'
REPORT_SIZE_MARKER_DEFINE = 'DEFINE'

DEBUG_PRINT = 'PRINT'
DEBUG_PLOT = 'PLOT'

READ_IMAGE_GRAY = 'GRAY'
READ_IMAGE_GREY = 'GRAY'
READ_IMAGE_RGB = 'RGB'
READ_IMAGE_NATIVE = 'NATIVE'
READ_IMAGE_RGBA = "RGBA"

WHITE_BALANCE_HIST = 'HIST'
WHITE_BALANCE_MAX = 'MAX'

AUTO_CROP_COLOR_IMAGE = 'IMAGE'
AUTO_CROP_COLOR_BLACK = 'BLACK'
AUTO_CROP_COLOUR_IMAGE = 'IMAGE'
AUTO_CROP_COLOUR_BLACK = 'BLACK'
AUTO_CROP_COLOR_WHITE = 'WHITE'
AUTO_CROP_COLOUR_WHITE = 'WHITE'

TRANSFORM_FIND_CC_NORMAL = 'normal'
TRANSFORM_FIND_CC_OTSU = 'otsu'
TRANSFORM_FIND_CC_AGAUSS = 'adaptgauss'
TRANSFORM_BACKGROUND_DARK = 'dark'
TRANSFORM_BACKGROUND_LIGHT = 'light'

VISUALIZE_BACKGROUND_BLACK = 'BLACK'
VISUALIZE_BACKGROUND_WHITE = 'WHITE'
VISUALIZE_BACKGROUND_GREY = 'IMAGE'
VISUALIZE_BACKGROUND_GRAY = 'IMAGE'
VISUALIZE_BACKGROUND_IMAGE = 'IMAGE'


## collect cv2 version info
try:
    CV2MAJOR, CV2MINOR, _, _ = cv2.__version__.split('.')
except:
    CV2MAJOR, CV2MINOR, _ = cv2.__version__.split('.')
CV2MAJOR, CV2MINOR = int(CV2MAJOR), int(CV2MINOR)